SELECT * FROM FND_ID_FLEX_SEGMENTS_VL WHERE rownum < 100;

SELECT * 
FROM all_views 
WHERE view_name = 'FND_ID_FLEX_SEGMENTS_VL' 
/
-- Show Flexfield segment label from the TL table
SELECT B.ROWID ROW_ID,
  B.ADDITIONAL_WHERE_CLAUSE,
  B.APPLICATION_ID,
  B.ID_FLEX_CODE,
  B.ID_FLEX_NUM,
  B.APPLICATION_COLUMN_NAME ,
  B.SEGMENT_NAME,
  B.LAST_UPDATE_DATE,
  B.LAST_UPDATED_BY ,
  B.CREATION_DATE,
  B.CREATED_BY,
  B.LAST_UPDATE_LOGIN ,
  B.SEGMENT_NUM,
  B.APPLICATION_COLUMN_INDEX_FLAG,
  B.ENABLED_FLAG ,
  B.REQUIRED_FLAG,
  B.DISPLAY_FLAG,
  B.DISPLAY_SIZE,
  B.SECURITY_ENABLED_FLAG ,
  B.MAXIMUM_DESCRIPTION_LEN,
  B.CONCATENATION_DESCRIPTION_LEN,
  B.FLEX_VALUE_SET_ID,
  /*
  B.RANGE_CODE,
  B.DEFAULT_TYPE,
  B.DEFAULT_VALUE,
  B.RUNTIME_PROPERTY_FUNCTION,
  */
  T.FORM_LEFT_PROMPT,
  T.FORM_ABOVE_PROMPT,  --This one will be used in defining the displayed label
  T.DESCRIPTION
FROM FND_ID_FLEX_SEGMENTS_TL T,
  FND_ID_FLEX_SEGMENTS B
WHERE B.APPLICATION_ID        = T.APPLICATION_ID
AND B.ID_FLEX_CODE            = T.ID_FLEX_CODE
AND B.ID_FLEX_NUM             = T.ID_FLEX_NUM
AND B.APPLICATION_COLUMN_NAME = T.APPLICATION_COLUMN_NAME
AND T.LANGUAGE                = userenv('LANG')
AND B.ID_FLEX_CODE = 'GL#'
/