select   AP.APPLICATION_SHORT_NAME
,        F.ID_FLEX_CODE
,        F.ID_FLEX_NAME
,        count(distinct FS.ID_FLEX_NUM)  NUM_OF_STRUCTURE
from     APPLSYS.FND_ID_FLEXS  F
,        APPLSYS.FND_ID_FLEX_STRUCTURES FS
,        APPS.FND_APPLICATION_VL AP
where    F.ID_FLEX_CODE = FS.ID_FLEX_CODE
and      F.APPLICATION_ID = AP.APPLICATION_ID
group by AP.APPLICATION_SHORT_NAME, F.ID_FLEX_CODE, F.ID_FLEX_NAME
order by 1,2
;